product_detailed:
    path:     /product/{id}
    methods: ['GET']
    defaults:
        _controller: 'Dixons\Http\Action\GetDetailedProduct'

product_confidential:
    path:     /admin/product/{id}
    methods: ['GET']
    defaults:
        _controller: 'Dixons\Http\Action\GetConfidentialProduct'
