product_detailed:
    path:     /product/{id}
    method: GET
    defaults:
        _controller: '\Dixons\Http\Action\GetDetailedProduct'

product_confidential:
    path:     /admin/product/{id}
    method: GET
    defaults:
        _controller: '\Dixons\Http\Action\GetConfidentialProduct'
