parameters:
    default_ttl_sec: 3600
    cache_dir: "%kernel.dir%/../../var/cache"
services:
    elastic_mock_driver:
        class: Dixons\Implementation\Persistence\EchoMockedElasticSearchDriver
    mysql_mock_driver:
        class: Dixons\Implementation\Persistence\EchoMockedMySQLDriver
    product_factory:
        class: Dixons\Implementation\Product\Factory\ProductFactory
    app_clock:
        class: Dixons\Implementation\Time\Clock

    product_query:
        class: Dixons\Implementation\Product\Query\ProductQuery
        arguments:
            - '@elastic_mock_driver'
            - '@mysql_mock_driver'
            - '@product_factory'

    product_cache_filesystem:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            - 'product'
            - '%default_ttl_sec%'
            - '%cache_dir%'

    product_query_cached:
        class: Dixons\Implementation\Product\Query\ProductQueryCacheDecorator
        decorates: 'product_query'
        arguments:
            - '@product_query.inner'
            - '@product_cache_filesystem'
            - '@app_clock'
