parameters:
    default_ttl_sec: 3600
    cache_dir: "%kernel.dir%/../../var/cache"

services:
    elastic_mock_driver:
        class: Dixons\Implementation\Persistence\EchoMockedElasticSearchDriver
    mysql_mock_driver:
        class: Dixons\Implementation\Persistence\EchoMockedMySQLDriver
    product_factory:
        class: Dixons\Implementation\Product\Factory\ProductFactory
    logger:
        class: Dixons\Implementation\Logging\MockLogger
    app_clock:
        class: Dixons\Implementation\Time\Clock

    product_stats:
        class: Dixons\Implementation\Product\Analysis\ProductStatistics
        arguments:
            - '@mysql_mock_driver'

    encoder_json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    normalizer_property:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer

    serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ['@normalizer_property']
            - ['@encoder_json']

    product_query:
        class: Dixons\Implementation\Product\Query\ProductQuery
        arguments:
            - '@elastic_mock_driver'
            - '@mysql_mock_driver'
            - '@product_factory'

    product_cache_filesystem:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            - 'product'
            - '%default_ttl_sec%'
            - '%cache_dir%'

    product_query_cached:
        class: Dixons\Implementation\Product\Query\ProductQueryCacheDecorator
        decorates: 'product_query'
        arguments:
            - '@product_query_cached.inner'
            - '@product_cache_filesystem'
            - '@app_clock'

    command_product_request_counter_handler:
        class: Dixons\Application\Product\Command\IncreaseRequestCountHandler
        arguments:
            - '@product_stats'

    command_bus:
        class: Dixons\Implementation\CommandBus\SimpleCommandBus
        calls:
            - [registerHandler, ['Dixons\Application\Product\Command\IncreaseRequestCount','@command_product_request_counter_handler']]

    command_bus_logger:
        class: Dixons\Implementation\CommandBus\CommandBusLoggerDecorator
        decorates: 'command_bus'
        arguments:
            - '@command_bus_logger.inner'
            - '@logger'

    action_product_base:
        class: Dixons\Http\Action\GetDetailedProduct
        abstract: true
        arguments:
            - '@product_query'
            - '@serializer'

    Dixons\Http\Action\GetDetailedProduct:
        class: Dixons\Http\Action\GetDetailedProduct
        parent: action_product_base
        public: true
        arguments:
            - '@command_bus'
            - '@logger'

    Dixons\Http\Action\GetConfidentialProduct:
        class: Dixons\Http\Action\GetConfidentialProduct
        parent: action_product_base
        public: true
        arguments:
            - '@command_bus'
            - '@logger'